name: Build Signed APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/brahman.keystore
          echo "✅ Keystore ready"

      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease --no-daemon --stacktrace
        timeout-minutes: 35

      - name: Locate APK
        run: |
          echo "📦 Finding APK..."
          find . -name "*.apk" -type f
          cp app/build/outputs/apk/release/app-release.apk BrahmanDownloader.apk
          ls -lh BrahmanDownloader.apk
          echo "✅ APK ready!"

      - name: Verify Signature
        run: |
          BUILD_TOOLS=$(ls $ANDROID_HOME/build-tools | sort -V | tail -1)
          $ANDROID_HOME/build-tools/$BUILD_TOOLS/apksigner verify --verbose BrahmanDownloader.apk
          echo "✅ Signature verified!"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BrahmanDownloader-APK
          path: BrahmanDownloader.apk
          retention-days: 30
